namespace WinAcmeGui.UI;

/// <summary>
/// Small helpers for building the window in code. The layout is hand-written rather
/// than generated by the designer so that changes show up as a readable diff.
/// </summary>
internal static class Ui
{
    public const int Gap = 8;

    /// <summary>A two column label/control grid that grows downwards.</summary>
    public static TableLayoutPanel Grid()
    {
        var grid = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            ColumnCount = 2,
            Padding = new Padding(Gap, Gap / 2, Gap, Gap / 2),
        };

        grid.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
        grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));

        return grid;
    }

    /// <summary>Adds a labelled row, with an optional grey hint underneath the control.</summary>
    public static void AddRow(TableLayoutPanel grid, string label, Control control, string? help = null)
    {
        var caption = new Label
        {
            Text = label,
            AutoSize = true,
            Anchor = AnchorStyles.Left,
            Margin = new Padding(0, 6, Gap, 0),
        };

        Stretch(control);

        grid.Controls.Add(caption, 0, grid.RowCount);
        grid.Controls.Add(control, 1, grid.RowCount);
        grid.RowCount++;

        if (!string.IsNullOrEmpty(help))
        {
            AddHint(grid, help);
        }
    }

    /// <summary>Adds a full width control with no label, such as a checkbox.</summary>
    public static void AddFullWidth(TableLayoutPanel grid, Control control, string? help = null)
    {
        Stretch(control);

        grid.Controls.Add(control, 0, grid.RowCount);
        grid.SetColumnSpan(control, 2);
        grid.RowCount++;

        if (!string.IsNullOrEmpty(help))
        {
            AddHint(grid, help);
        }
    }

    /// <summary>
    /// Anchors a control to both edges instead of docking it. Docking inside an
    /// auto-sized row collapses multiline boxes to their minimum height; anchoring
    /// stretches the width but leaves an explicitly set height alone.
    /// </summary>
    private static void Stretch(Control control)
    {
        control.Anchor = AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Top;
        control.Margin = new Padding(0, 3, 0, 3);
    }

    public static void AddHint(TableLayoutPanel grid, string text)
    {
        var hint = new Label
        {
            Text = text,
            AutoSize = true,
            ForeColor = SystemColors.GrayText,
            Margin = new Padding(0, 0, 0, 6),
        };

        grid.Controls.Add(hint, 1, grid.RowCount);
        grid.RowCount++;
    }

    public static GroupBox Group(string title, Control content)
    {
        var box = new GroupBox
        {
            Text = title,
            Dock = DockStyle.Fill,
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            Padding = new Padding(Gap, Gap, Gap, Gap),
            Margin = new Padding(0, 0, 0, Gap),
        };

        box.Controls.Add(content);
        return box;
    }

    /// <summary>
    /// A group box that fills the space it is given rather than shrinking to its
    /// content — for the output pane, which should take whatever is left.
    /// </summary>
    public static GroupBox GroupFill(string title, Control content)
    {
        var box = new GroupBox
        {
            Text = title,
            Dock = DockStyle.Fill,
            Padding = new Padding(Gap, Gap, Gap, Gap),
            Margin = new Padding(0, 0, 0, Gap),
        };

        content.Dock = DockStyle.Fill;
        box.Controls.Add(content);
        return box;
    }

    public static TextBox Text(bool multiline = false, int height = 0)
    {
        var box = new TextBox { Multiline = multiline };

        if (multiline)
        {
            box.ScrollBars = ScrollBars.Vertical;
            box.Height = height > 0 ? height : 80;
        }

        return box;
    }

    /// <summary>A read-only pane for log output and the command preview.</summary>
    public static TextBox ReadOnlyPane(int height = 0)
    {
        return new TextBox
        {
            Multiline = true,
            ReadOnly = true,
            ScrollBars = ScrollBars.Both,
            WordWrap = false,
            BackColor = SystemColors.Window,
            Font = new Font(FontFamily.GenericMonospace, 8.5f),
            Height = height > 0 ? height : 120,
        };
    }

    public static Button Button(string text, EventHandler onClick, bool isDefault = false)
    {
        var button = new Button
        {
            Text = text,
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            Padding = new Padding(Gap, 2, Gap, 2),
            Margin = new Padding(0, 0, Gap, 0),
        };

        if (isDefault)
        {
            button.Font = new Font(button.Font, FontStyle.Bold);
        }

        button.Click += onClick;
        return button;
    }
}
